### ISSUE TITLE
Menambahkan Tautan Demo Aplikasi dan Format Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [Zuans/Kobok#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Juan. Mas juga sudah menambahkan beberapa gaya sendiri. _Copywrite_ notifikasinya juga cukup menarik. :smile: 

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Menambahkan Tautan ke Demo Aplikasi
Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.

2. Format Penulisan Kode
https://github.com/Zuans/Kobok/blob/df488e0716e00f7af839a86f6048f355aa20439e/src/components/AppKodeKotak.vue#L4-L7

Pada bagian tersebut sepertinya kodenya kurang terformat denagn baik Mas, biasanya hal tersebut dikarenakan format otomatis dari eslint. Mungkin Mas bisa memformatnya secara manual sehingga kurang lebih kodenya menjadi seperti berikut:

```html
        <AppTombol 
            @btn-click="hapusKode(kodeId)"
            bgColor="danger"
        >
          Delete
        </AppTombol>
```

Dan pada bagian berikut:

https://github.com/Zuans/Kobok/blob/df488e0716e00f7af839a86f6048f355aa20439e/src/components/AppKodeKotak.vue#L12-L19

Menurut saya akan lebih baik diberi jarak antara bagian kode import dengan export, sehingga akan meningkatkan keterbacaan.

Semangat selalu Mas! :muscle:

**Comment by Zuans** [comment]
> Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Juan. Mas juga sudah menambahkan beberapa gaya sendiri. _Copywrite_ notifikasinya juga cukup menarik. 
> 
> Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni
> 
> 1. Menambahkan Tautan ke Demo Aplikasi
>    Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas
> 
> ![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)
> 
> Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.
> 
> 1. Format Penulisan Kode
>    https://github.com/Zuans/Kobok/blob/df488e0716e00f7af839a86f6048f355aa20439e/src/components/AppKodeKotak.vue#L4-L7
> 
> Pada bagian tersebut sepertinya kodenya kurang terformat denagn baik Mas, biasanya hal tersebut dikarenakan format otomatis dari eslint. Mungkin Mas bisa memformatnya secara manual sehingga kurang lebih kodenya menjadi seperti berikut:
> 
> ```
>         <AppTombol 
>             @btn-click="hapusKode(kodeId)"
>             bgColor="danger"
>         >
>           Delete
>         </AppTombol>
> ```
> 
> Dan pada bagian berikut:
> 
> https://github.com/Zuans/Kobok/blob/df488e0716e00f7af839a86f6048f355aa20439e/src/components/AppKodeKotak.vue#L12-L19
> 
> Menurut saya akan lebih baik diberi jarak antara bagian kode import dengan export, sehingga akan meningkatkan keterbacaan.
> 
> Semangat selalu Mas!

Terimakasih banyak mas jefry atas sarannya, proyek yang saya buat ini sudah saya ubah sesuai saran dari mas jefry jadi issue nya saya tutup aja ya
